name: Build and deploy JAR app to Azure Web App  
  
env:    
  AZURE_WEBAPP_NAME: app-printpoisoning-bookfull-api  # set this to the name of your Azure Web App    
  JAVA_VERSION: '21'                  # set this to the Java version to use    
  DISTRIBUTION: zulu                  # set this to the Java distribution  
  
on:    
  push:      
    branches: [ "dev" ]    
  workflow_dispatch:  
  
permissions:    
  contents: read  
  
jobs:    
  build:      
    runs-on: ubuntu-latest  
    steps:        
      - uses: actions/checkout@v3  
        
      - name: Set up Java version          
        uses: actions/setup-java@v4          
        with:            
          java-version: ${{ env.JAVA_VERSION }}            
          distribution: ${{ env.DISTRIBUTION }}            
          cache: 'gradle'  
  
      - name: Grant execute permission for gradlew  
        run: chmod +x gradlew  
        
      - name: Build with Gradle            
        run: ./gradlew clean build    
  
      - name: Upload artifact for deployment job          
        uses: actions/upload-artifact@v4          
        with:            
          name: java-app            
          path: 'build/libs/*.jar'  # Adjust this path if needed  
  
  deploy:      
    permissions:        
      contents: none      
    runs-on: ubuntu-latest      
    needs: build      
    environment:        
      name: 'Development'        
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}  
  
    steps:        
      - name: Download artifact from build job          
        uses: actions/download-artifact@v4          
        with:            
          name: java-app  
  
      - name: Deploy to Azure Web App          
        id: deploy-to-webapp          
        uses: azure/webapps-deploy@v2          
        with:            
          app-name: ${{ env.AZURE_WEBAPP_NAME }}            
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}            
          package: '*.jar'  
