name: Build and Deploy to Azure App Service  
  
on:  
  push:  
    branches:  
      - dev  # dev 브랜치에 푸시될 때 트리거  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout repository  
      uses: actions/checkout@v2  
  
    - name: Set up JDK 21  
      uses: actions/setup-java@v1  
      with:  
        java-version: '21'  
  
    - name: Grant execute permission for gradlew  
      run: chmod +x gradlew  
  
    - name: Build with Gradle  
      run: ./gradlew build  
  
    - name: Upload artifact for deployment job  
      uses: actions/upload-artifact@v2  
      with:  
        name: build-artifact  
        path: build/libs/**/*.jar  
  
  deploy:  
    runs-on: ubuntu-latest  
    needs: build  
  
    steps:  
    - name: Download artifact from build job  
      uses: actions/download-artifact@v2  
      with:  
        name: build-artifact  
  
    - name: 'Login to Azure'  
      uses: azure/login@v1  
      with:  
        creds: ${{ secrets.AZURE_CREDENTIALS }}  
  
    - name: 'Deploy to Azure WebApp'  
      uses: azure/webapps-deploy@v2  
      with:  
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}  
        package: '*.jar'  
